Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/07/2017
Var
    salarioatualizado,percentagem,salarioantigo:real


Inicio
      leia(salarioantigo,percentagem)
      salarioatualizado<-(salarioantigo*percentagem)
      Escreva(Salarioatualizado)



Fimalgoritmo