Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/07/2017
Var
    baseM,baseM2,altura,areaT:real


Inicio
      Leia(baseM,baseM2,Altura)
      areat<-(baseM+baseM2)*Altura/2
      Escreva(AreaT)


Fimalgoritmo