Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/07/2017
Var
   Largura,comprimento,altura,volume:real


Inicio
      Leia(comprimento,largura,altura)
      Volume<-(Largura*comprimento)*Altura
      Escreva(volume)


Fimalgoritmo