Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/07/2017
Var
    nota1,nota2,nota3,medida:real


Inicio
      Leia(nota1,nota2,nota3)
      medida<-(nota1+nota2+nota3)/3
      Escreva(medida)


Fimalgoritmo